#!/usr/bin/env python3
"""Derive the two installed app icons from the master drawing.

`data/icons/logo.svg` is the Inkscape master and the only file an artist edits.
The hicolor icons the app actually installs used to be hand-copied from it, so
they went stale the moment the master changed. This regenerates both.

Inkscape does the one step a stylesheet cannot: `object-stroke-to-path` turns
every stroke into a filled outline, which is what a symbolic icon has to be
(GNOME recolours symbolics by setting a fill, so a stroked glyph would not
follow the theme). After that pass each drawn path carries a flat fill, and the
two icons are just two selections of those paths:

  scalable  every path, its own colour, scaled into a 128 px box
  symbolic  the outlines only, in `currentColor`, scaled into a 16 px box

An outline is recognised by its fill being the master's stroke colour. That also
drops the master's drop shadow, which is a second stroke in a near-black of its
own and has no room to read at 16 px.

Usage: build-aux/derive-icons.py [--check]
"""

import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

SVG = "{http://www.w3.org/2000/svg}"

ROOT = Path(__file__).resolve().parent.parent
MASTER = ROOT / "data/icons/logo.svg"
APP_ID = "io.github.stroblme.Accent"
SCALABLE = ROOT / f"data/icons/hicolor/scalable/apps/{APP_ID}.svg"
SYMBOLIC = ROOT / f"data/icons/hicolor/symbolic/apps/{APP_ID}-symbolic.svg"

# The master's stroke colour. Every outline inherits it when strokes become
# paths, so it is what tells an outline apart from a flat fill or the shadow.
OUTLINE = "#5d5d5d"
# The master's canvas, and the two icon sizes the hicolor theme wants.
CANVAS = 256


def flatten(svg: Path) -> list[tuple[str, str]]:
    """Every drawn path in document order, as (fill, d)."""
    out: list[tuple[str, str]] = []

    def walk(el):
        for child in el:
            tag = child.tag.replace(SVG, "")
            if tag == "g":
                walk(child)
            elif tag == "path" and child.get("d"):
                style = dict(
                    pair.split(":", 1)
                    for pair in (child.get("style") or "").split(";")
                    if ":" in pair
                )
                fill = child.get("fill") or style.get("fill", "none")
                out.append((fill.strip().lower(), child.get("d")))

    walk(ET.parse(svg).getroot())
    return out


def stroke_to_path(master: Path, into: Path) -> list[tuple[str, str]]:
    subprocess.run(
        [
            "inkscape",
            # `object-to-path` first, because `flatten` only reads <path>: the master's
            # background is a <rect>, and without this pass it is silently dropped and the
            # scalable icon comes out with no background at all.
            "--actions=select-all;object-to-path;object-stroke-to-path;"
            f"export-filename:{into};export-plain-svg;export-overwrite;export-do",
            str(master),
        ],
        check=True,
        capture_output=True,
    )
    return flatten(into)


def render(paths: list[tuple[str, str]], size: int, symbolic: bool) -> str:
    scale = size / CANVAS
    head = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- Generated by build-aux/derive-icons.py from data/icons/logo.svg."
        " Do not edit. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}"'
        f' viewBox="0 0 {size} {size}">\n'
    )
    group = (
        f'  <g fill="currentColor" transform="scale({scale})">\n'
        if symbolic
        else f'  <g transform="scale({scale})">\n'
    )
    body = "".join(
        f'    <path d="{d}"/>\n' if symbolic else f'    <path fill="{fill}" d="{d}"/>\n'
        for fill, d in paths
    )
    return head + group + body + "  </g>\n</svg>\n"


def main() -> int:
    check = "--check" in sys.argv
    with tempfile.TemporaryDirectory() as tmp:
        paths = stroke_to_path(MASTER, Path(tmp) / "flat.svg")
    if not paths:
        print(f"{MASTER}: no paths after stroke-to-path", file=sys.stderr)
        return 1

    outlines = [p for p in paths if p[0] == OUTLINE]
    if not outlines:
        print(
            f"{MASTER}: no path is filled {OUTLINE}, so the symbolic would be"
            " empty. Update OUTLINE in this script to the master's stroke colour.",
            file=sys.stderr,
        )
        return 1

    wanted = {
        SCALABLE: render(paths, 128, symbolic=False),
        SYMBOLIC: render(outlines, 16, symbolic=True),
    }
    stale = [p for p, text in wanted.items() if not p.exists() or p.read_text() != text]
    if check:
        for path in stale:
            print(f"{path.relative_to(ROOT)} is out of date")
        return 1 if stale else 0
    for path, text in wanted.items():
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
